# Generated by Django 5.1.3 on 2024-12-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miportafolio', '0002_remove_contactmessage_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
